apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident-product-deployment
  labels:
    app: trident
spec:
  selector:
    matchLabels:
      app: trident
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: trident
    spec:
      containers:
        - image: gkgarry911/trident-product-service:0.0.1
          name: trident-product-service
          ports:
          - containerPort: 4001
          # restartPolicy: Always
          imagePullPolicy: Always
          # resources:
          #   requests:
          #     cpu: "20m"
          #     memory: "55M"
          # livenessProbe:
          #   httpGet:
          #     path: /_status/healthz
          #     port: 5000
          #   initialDelaySeconds: 90
          #   timeoutSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /_status/healthz
          #     port: 5000
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 10
          # env:
          # - name:  ENVVARNAME
          #   value:  ENVVARVALUE       
          # volumeMounts:
          # - mountPath: /data
          #   name: data
        # volumes:
        #   - name: data
        #     emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: trident-product-service
spec:
  selector:
    app: trident
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 4001
      targetPort: 4001
