apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  trident-product-service
  labels:
    name:  trident
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  trident
    spec:
      containers:
      - image:  gkgarry911/trident-product-service:0.0.1
        name:  gkgarry911/trident-product-service
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        # livenessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        # env:
        # - name:  ENVVARNAME
        #   value:  ENVVARVALUE       
        ports:
        - containerPort:  4001
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always